<?php

require './templates/header.phtml';


?>
<form method="POST">
  <div class="form-group">
    <label>Usuario(webadmin)</label>
    <input required type="text" class="form-control" id="exampleInputEmail1" name= "user" aria-describedby="emailHelp" placeholder="Ingrese el usuario">
    
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">contraseña(admin)</label>
    <input required type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password">
  </div>
     
  <?php if ($error) : ?>
              <div class='alert alert-danger' role='alert'>
                  <?= $error ?>
              </div> 
          <?php endif ?>
  
  <button type="submit" class="btn btn-primary">Ingresar</button>
</form>


<?php
require './templates/footer.phtml';



?>